config/routes.rb
TenureAndPromotion::Application.routes.draw do

  resources :issues
  get 'issues/new'

  get 'issues/create'

  get 'issues/done'

  resources :user_roles
  resources :levels
  resources :recusals

  get 'home/index'

  get 'context/:user_id', to: 'users#contextualize'

  get 'submit', to: 'categories#phase_complete'

  resources :roles

  resources :departments

  resources :sections

  resources :department_sections

  resources :colleges

  get 'cal', to: "cal#index"

  mount FullcalendarEngine::Engine => "/calendar"
  root 'home#index'
  get '/license', to: 'start#index'
  get '/logout', to: 'start#logout'
  get '/set_role', to: 'start#set_role'
  get '/contact', to: 'contact#index'
  resources :users
  resources :categories do
    resources :uploads do
      post :update_row_order, on: :collection
    end
  end
  get '/compile/:category/:upload', to: 'compile#reciprocal'
  get '/compile', to: 'compile#index'
  get '/compile/begin', to: 'compile#begin'
  get '/compile/compile', to: 'compile#compile'

end

app/models/issue.rb
require 'active_resource'

class RedmineCollection < ActiveResource::Collection
  def initialize(parsed = {})
    @elements = parsed.values.first
  end
end

class Issue < ActiveResource::Base
  self.site = ENV["REDMINE_SERVER"]
  self.user = ENV["REDMINE_USER"]
  self.password = ENV["REDMINE_PASSWORD"]
  self.collection_parser = RedmineCollection
  self.include_root_in_json = true
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  def create
    @issue = Issue.new(issue_params)

    if @issue.save
      redirect_to @issue, notice: 'Issue was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /issues/1
  def update
    if @issue.update(issue_params)
      redirect_to @issue, notice: 'Issue was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /issues/1
  def destroy
    @issue.destroy
    redirect_to issues_url, notice: 'Issue was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def issue_params
      params.require(:issue).permit(:subject, :description)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= bootstrap_form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :subject %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Issues</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>