config/routes.rb
TenureAndPromotion::Application.routes.draw do

  resources :issues
  get 'issues/new'

  get 'issues/create'

  get 'issues/done'

  resources :user_roles
  resources :levels
  resources :recusals

  get 'home/index'

  get 'context/:user_id', to: 'users#contextualize'

  get 'submit', to: 'categories#phase_complete'

  resources :roles

  resources :departments

  resources :sections

  resources :department_sections

  resources :colleges

  get 'cal', to: "cal#index"

  mount FullcalendarEngine::Engine => "/calendar"
  root 'home#index'
  get '/license', to: 'start#index'
  get '/logout', to: 'start#logout'
  get '/set_role', to: 'start#set_role'
  get '/contact', to: 'contact#index'
  resources :users
  resources :categories do
    resources :uploads do
      post :update_row_order, on: :collection
    end
  end
  get '/compile/:category/:upload', to: 'compile#reciprocal'
  get '/compile', to: 'compile#index'
  get '/compile/begin', to: 'compile#begin'
  get '/compile/compile', to: 'compile#compile'

end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]

  # GET /levels
  def index
    @levels = Level.all
  end

  # GET /levels/1
  def show
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  # POST /levels
  def create
    @level = Level.new(level_params)

    if @level.save
      redirect_to @level, notice: 'Level was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /levels/1
  def update
    if @level.update(level_params)
      redirect_to @level, notice: 'Level was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /levels/1
  def destroy
    @level.destroy
    redirect_to levels_url, notice: 'Level was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def level_params
      params.require(:level).permit(:name, :level)
    end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/levels/_form.html.erb
<%= form_for(@level) do |f| %>
  <% if @level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
      <% @level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing Level</h1>

<%= render 'form' %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Levels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.name %></td>
        <td><%= level.level %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<h1>New Level</h1>

<%= render 'form' %>

<%= link_to 'Back', levels_path %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @level.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @level.level %>
</p>

<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', levels_path %>