config/routes.rb
TenureAndPromotion::Application.routes.draw do

  resources :issues
  get 'issues/new'

  get 'issues/create'

  get 'issues/done'

  resources :user_roles
  resources :levels
  resources :recusals

  get 'home/index'

  get 'context/:user_id', to: 'users#contextualize'

  get 'submit', to: 'categories#phase_complete'

  resources :roles

  resources :departments

  resources :sections

  resources :department_sections

  resources :colleges

  get 'cal', to: "cal#index"

  mount FullcalendarEngine::Engine => "/calendar"
  root 'home#index'
  get '/license', to: 'start#index'
  get '/logout', to: 'start#logout'
  get '/set_role', to: 'start#set_role'
  get '/contact', to: 'contact#index'
  resources :users
  resources :categories do
    resources :uploads do
      post :update_row_order, on: :collection
    end
  end
  get '/compile/:category/:upload', to: 'compile#reciprocal'
  get '/compile', to: 'compile#index'
  get '/compile/begin', to: 'compile#begin'
  get '/compile/compile', to: 'compile#compile'

end

app/models/college.rb
class College < ActiveRecord::Base
  has_many :departments, dependent: :destroy
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  def index
    @colleges = College.all
  end

  # GET /colleges/1
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  def create
    @college = College.new(college_params)

    if @college.save
      redirect_to @college, notice: 'College was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /colleges/1
  def update
    if @college.update(college_params)
      redirect_to @college, notice: 'College was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /colleges/1
  def destroy
    @college.destroy
    redirect_to colleges_url, notice: 'College was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def college_params
      params.require(:college).permit(:name)
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.slim
.row
  .col-xs-4
    = bootstrap_form_for @college do |f|
      - if @college.errors.any?
        #error_explanation
          h2 = "#{pluralize @college.errors.count, "error"} prohibited this college from being saved:"
          ul
            - @college.errors.full_messages.each do |message|
              li = message
    
      = f.text_field :name
      = f.primary

app/views/colleges/edit.html.slim
h1 Editing college

== render 'form'

br

= link_to 'Back', colleges_path, class: 'btn btn-warning'
br

app/views/colleges/index.html.slim
h1 Select College 

table class=["table table-striped"]
  thead
    tr
      th Name

  tbody
    - @colleges.each do |college|
      tr
        td = link_to college.name, users_path(college: college.id, role: params[:role])
        - if role.tech_user?
          td = link_to 'Edit', edit_college_path(college), class: 'badge alert-warning'
          td = link_to raw('<em class="fa fa-trash-o"></em> Destroy'), college, data: {:confirm => 'Are you sure?'},
        :method => :delete, class: 'badge alert-danger'
br

app/views/colleges/new.html.slim
h1 New college

== render 'form'
br
= link_to 'Cancel', colleges_path, class: 'btn btn-warning'

app/views/colleges/show.html.slim
p#notice = notice

p
  strong Name:
  = @college.name

= link_to 'Edit', edit_college_path(@college)
'|
= link_to 'Back', colleges_path