config/routes.rb
TenureAndPromotion::Application.routes.draw do

  resources :issues
  get 'issues/new'

  get 'issues/create'

  get 'issues/done'

  resources :user_roles
  resources :levels
  resources :recusals

  get 'home/index'

  get 'context/:user_id', to: 'users#contextualize'

  get 'submit', to: 'categories#phase_complete'

  resources :roles

  resources :departments

  resources :sections

  resources :department_sections

  resources :colleges

  get 'cal', to: "cal#index"

  mount FullcalendarEngine::Engine => "/calendar"
  root 'home#index'
  get '/license', to: 'start#index'
  get '/logout', to: 'start#logout'
  get '/set_role', to: 'start#set_role'
  get '/contact', to: 'contact#index'
  resources :users
  resources :categories do
    resources :uploads do
      post :update_row_order, on: :collection
    end
  end
  get '/compile/:category/:upload', to: 'compile#reciprocal'
  get '/compile', to: 'compile#index'
  get '/compile/begin', to: 'compile#begin'
  get '/compile/compile', to: 'compile#compile'

end

app/models/category.rb
class Category < ActiveRecord::Base

  include RankedModel

  # Categories belong to a level
  belongs_to :level

  # Categories may need to be re-ordered
  ranks :row_order

  # Each user has Categories
  belongs_to :user
  # Each category has files (Uploads) attached to it
  has_many :uploads, dependent: :destroy
  has_many :converts, dependent: :destroy

  def pdf?
    Section.find_by_name(name).pdf
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_filter :check_phase!

  add_crumb 'Dossier', '/sections'
  # GET /categories
  def index
    #Categories each belong to a user
    @categories = @user.categories.rank(:row_order).select { |category| role.level == category.level } 
    @total = @categories.map{ |c| c.uploads.length}.reduce(:+)
    @button = button
    redirect_to compile_path if @categories.empty?
  end

  # GET /categories/1
  def show
    add_crumb @category.name, category_path
  end

  # GET /categories/new
  def new
    add_crumb 'New Section', new_category_path
    @category = @user.categories.new
  end

  # GET /categories/1/edit
  def edit
    add_crumb @category.name, category_path
  end

  # POST /categories
  def create
    @category = @user.categories.new category_params

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    add_crumb @category.name, category_path
    if @category.update category_params
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  def phase_complete
    @user.phase_complete!
    if @user[:phase].odd?
      redirect_to contact_path, notice: "This dossier was submitted to the #{@user.phase.titleize}."
    else
      redirect_to categories_path, notice: "This dossier was closed to the committee."
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      set_user
      @category = @user.categories.find params[:id]
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit :name, :user_id
    end

    def set_user
      @user = context_user
    end

    def button
      [:text, :confirm].zip({ department_committee: ["Submit final Dossier to Department Committee", "I acknowledge that my dossier is complete and ready for review. Any additional changes must be made through an administrator"],
        department_admin: ["Close Dossier to Department Committee", "This will close the dossier permanently to the Department Committee staff, so only the admin and chair can view the Dossier."],
        college_committee: ["Submit final Dossier to College Committee", "I acknowledge that all Department documents are correctly entered and are ready for review by the College. Any further changes must be made through an administrator."],
        college_admin: ["Close Dossier to College Commitee", "This will close the dossier permanently to the College Commitee staff, so only the admin and dean can view the Dossier."],
        provost_committee: ["Submit final Dossier to Provost Committee", "I acknowledge that all College documents are correctly entered and are ready for review by the Provost Committee. Any further changes must be made through and administrator."],
        provost_admin: ["Close Dossier to Provost Committee", "This will close the dossier permanently to the Provost Committee, so only the Provost Admin, Senior Vice Provost, and Provost may view the Dossier."],
        archive: ["Close and Archive final Dossier", "I acknowledge that all documents for this dossier are complete and correct, and have been fully reviewed. After clicking yes, this dossier will be archived and cannot be viewed or edited anymore through this application."]
      }[User.phases.key(context_user[:phase] + 1).to_sym]).to_h
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_downloadjs.html.erb
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade item" data-item-id="{%=file.id%}">
        <td>
            <span class="preview">
                {% if (file.thumbnail_url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnail_url%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnail_url?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.delete_url) { %}
                <button class="badge alert-danger delete" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="fa fa-trash-o"></i>
                    <span>Delete</span>
                </button>
            {% } else { %}
                <button class="badge alert-danger cancel">
                    <i class="fa fa-trash-o"></i>
                    <span>Delete</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_uploader.html.erb
 <%= form_for [@category, Upload.new], html: { multipart: true, id: "fileupload"  } do |f| %>
  <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
  <div class="row fileupload-buttonbar col-md-9">
    <div class="span7">
      <!-- The fileinput-button span is used to style the file input field as button -->
      <%= f.file_field :upload, class: 'hide'  %>
      <button type="submit" class="btn btn-primary start hide" id="save_all">
    </div>
    <div class="span5">
      <!-- The global progress bar -->
      <div class="progress progress-success progress-striped active fade">
        <div class="bar" style="width:0%;"></div>
      </div>
    </div>
  </div>
  <!-- The loading indicator is shown during image processing -->
  <div class="fileupload-loading"></div>
  <!-- The table listing the files available for upload/download -->
  <div class="row">
    <div class="col-md-4">
      <div class="well well-success" id="green_button"><h4><i class="fa fa-folder"></i> Click to add files...</h4></div>
    </div>
    <div class="col-md-1 text-center">
      <h4>OR</h4>
    </div>
    <div class="col-md-4">
      <div class="well"><h4><i class="fa fa-file"></i> Drag and drop files.</h4></div>
    </div>
    <div class="row">
      <div class="col-md-1 col-md-offset-9">
        <button class="btn btn-primary" id="blue_button"><i class="fa fa-upload"></i> Save All</button>
     </div>
   </div>
  </div>
  <table class="table table-bordered table-striped" id="sortable"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
  </table>
<% end %>
<script>
$('#green_button').bind("click" , function () {
  $('#upload_upload').click();
});

$('#blue_button').bind("click" , function (e) {
  e.preventDefault();
  $('#save_all').click();
});


var fileUploadErrors = {
maxFileSize: 'File is too big',
minFileSize: 'File is too small',
acceptFileTypes: 'Filetype not allowed',
maxNumberOfFiles: 'Max number of files exceeded',
uploadedBytes: 'Uploaded bytes exceed file size',
emptyResult: 'Empty file upload result'
};
</script>
<%= render 'uploadjs' %>
<%= render 'downloadjs' %>
<script>
sortable = function() {
  jQuery(function() {
    var cells, desired_width, table_width;
    if ($('#sortable').length > 0) {
      table_width = $('#sortable').width();
      cells = $('.table').find('tr')[0].cells.length;
      desired_width = table_width / cells + 'px';
      $('.table td').css('width', desired_width);
      return $('#sortable').sortable({
        axis: 'y',
        items: '.item',
        cursor: 'move',
        sort: function(e, ui) {
          return ui.item.addClass('active-item-shadow');
        },
        stop: function(e, ui) {
          ui.item.removeClass('active-item-shadow');
          return ui.item.children('td').effect('highlight', {}, 1000);
        },
        update: function(e, ui) {
          var item_id, position;
          item_id = ui.item.data('item-id');
          console.log(item_id);
          position = ui.item.index();
          return $.ajax({
            type: 'POST',
            url: '<%= update_row_order_category_uploads_path(@category.id) %>',
            dataType: 'json',
            data: {
              upload: {
                upload_id: item_id,
                row_order_position: position
              }
            }
          });
        }
      });
    }
  });

};
$(function () {
    // Initialize the jQuery File Upload widget:
    $('#fileupload').fileupload();
    //
    // Load existing files:
    $.getJSON($('#fileupload').prop('action'), function (files) {
      var fu = $('#fileupload').data('blueimpFileupload'),
      template;
      // This is broken for some reason
      //fu._adjustMaxNumberOfFiles(-files.length);
      console.log(files);
      template = fu._renderDownload(files)
        .appendTo($('#fileupload .files'));
      // Force reflow:
      fu._reflow = fu._transition && template.length &&
        template[0].offsetWidth;
      template.addClass('in');
      $('#loading').remove();
      }).done(function () { sortable(); });

});
</script>

app/views/categories/_uploadjs.html.erb
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="badge alert-primary start" disabled>
                    <i class="fa fa-upload"></i>
                    <span>Save</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="badge alert-danger cancel">
                    <i class="fa fa-trash-o"></i>
                    <span>Delete</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}</script>

app/views/categories/convert.html.erb
<!-- This shows when conversions are complete -->
<h1 class="text-center text-success">    <%= @counter %> file(s) converted</h1>
<h2 class="text-center"><%= link_to 'Continue', converts_path, :class => "text-primary" %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h2>Dossier Sections for <%= @user.name %></h2>
Click on each section name below to add files to that dossier section.
When you are ready to see your dossier, click "Preview Dossier" below.
If you are satisfied with your dossier, click "Submit Final Dossier" to send
your dossier to the department level for review.
<table class="table table-striped table-hover warning">
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><%= link_to category.name, category, class: 'display: block;' %></td>
      <td><span class="badge"><%= category.uploads.length %></span></td>
    </tr>
  <% end %>
    <tr>
      <td><strong>Total:</strong></td>
      <td><span class="badge"><%= @total %></span></td>
    </tr>
  </tbody>
</table>
<p>If you exit the application, saved items remain in your dossier.</p>
<div class="row">
  <div class="col-md-4"> 
  <%= link_to 'Preview Dossier', compile_path, class: 'btn btn-primary' %>
  </div>

  <% if role.candidate? || role.admin? %>
    <div class="col-md-4 col-md-offset-2">
      <%= link_to @button[:text], submit_path, class: 'btn btn-success', data: { confirm: @button[:confirm] } %> 
    </div>
  <% end %>
</div>
<script>
$(function () { $.fn.twitter_bootstrap_confirmbox.defaults = {
    fade: false,
    title: "Submit Final Dossier", // if title equals null window.top.location.origin is used
    cancel: "No",
    cancel_class: "btn cancel",
    proceed: "Yes",
    proceed_class: "btn proceed btn-primary"
} });
</script>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong>Section:</strong>
  <%= @category.name %>
</h2>

<%= render 'uploader' %>
<%= link_to 'Back to Dossier Sections', categories_path, class: "btn btn-warning" %>